### ISSUE TITLE
it works fine while using manually , but using the crontab it dumps the following log. can anyone help here

### ISSUE THREAD

**Issue by revdilip** [pageauc/rclone4pi#1]
/usr/bin/rclone listremotes
2018/04/20 05:18:02 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
+ /usr/bin/rclone listremotes
+ grep -l didDMC
2018/04/20 05:18:02 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
+ '[' 1 == 0 ']'
+ echo ---------------------------------------------------
---------------------------------------------------
+ echo 'ERROR : rcloneName=didDMC Does not Exist'
ERROR : rcloneName=didDMC Does not Exist
+ echo 'INFO  : List Remote Storage Names that are Setup.'
INFO  : List Remote Storage Names that are Setup.
+ echo 'rclone listremotes'
rclone listremotes
+ echo -------------------
-------------------
+ rclone listremotes

**Comment by pageauc** [comment]
Looks like you are running under root user.  I have updated the wiki https://github.com/pageauc/rclone4pi/wiki#how-to-automate-rclone  with the correct command to run under pi user.  My mistake.

    */5 * * * * su pi -c "/home/pi/rclone-sync.sh" > /dev/null 2>&1

Try similar crontab entry to above.  Let me know if this works OK 4U.  Claude ...

**Comment by revdilip** [comment]
Thanks a lot again.. It worked
