### ISSUE TITLE
How to uninstall rclone

### ISSUE THREAD

**Issue by bustroker** [pageauc/rclone4pi#2]
Hi, I'm moving rclone to a container, how can I uninstall it from my OS?
Thx

**Comment by pageauc** [comment]
You can remove default rclone install including config file per the following commands

    sudo rm /home/pi/.config/rclone/rclone.conf
    sudo rm /usr/bin/rclone
    sudo rm /usr/local/share/man/man1/rclone.1
   
For more details See wiki here https://github.com/pageauc/rclone4pi/wiki#how-to-remove-rclone

**Comment by bustroker** [comment]
thx

**Comment by pageauc** [comment]
See the wiki link  https://github.com/pageauc/rclone4pi/wiki#how-to-remove-rclone if you need to remove the remote storage rclone.conf file
